color0 #232031
color1 #fd4663
color2 #7a67e4
color3 #b15cd6
color4 #cc66bc
color5 #a093ec
color6 #d096e9
color7 #f2f2f3
color8 #656378
color9 #fd4663
color10 #7a67e4
color11 #b15cd6
color12 #cc66bc
color13 #a093ec
color14 #d096e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1a1825
background            #1a1825
foreground            #f2f2f3
selection_foreground  #b0afb6
selection_background  #232031
active_border_color   #7a67e4
inactive_border_color #232031
url_color             #7a67e4

active_tab_foreground   #1a1825
active_tab_background   #7a67e4
inactive_tab_foreground #b0afb6
inactive_tab_background #232031
cursor_trail_color      #b0afb6
