color0 #2c242d
color1 #fd4663
color2 #d270e6
color3 #5c5cd6
color4 #d5818f
color5 #dd92ec
color6 #9696e9
color7 #f3f2f3
color8 #746277
color9 #fd4663
color10 #d270e6
color11 #5c5cd6
color12 #d5818f
color13 #dd92ec
color14 #9696e9
color15 #f3f2f3

cursor                #f3f2f3
cursor_text_color     #211b22
background            #211b22
foreground            #f3f2f3
selection_foreground  #b5afb6
selection_background  #2c242d
active_border_color   #d270e6
inactive_border_color #2c242d
url_color             #d270e6

active_tab_foreground   #060407
active_tab_background   #d270e6
inactive_tab_foreground #b5afb6
inactive_tab_background #2c242d
cursor_trail_color      #b5afb6
